### ISSUE TITLE
Mudar ronda

### ISSUE THREAD

**Issue by dansreis** [Pigmoth69/Sketchnary-ANDROID#2]
Não temos nada para tratar rondas e mudar de rondas

**Comment by joaoDavidGB** [comment]
Acho que isto devia ser feito no servidor. Um ciclo que faz continue quando alguém acertar no desenho e muda o role do jogador que esta a desenhar para spectator e um spec para desenhador ou então ser sempre o mesmo a desenhar. Ao alterar o role mudasse a activity no android.
